image: gcc:latest

stages:
  - build
  - test

before_script:
  - mkdir build
  - cd build
  - cmake ../src/

build_job:
  stage: build
  script:
    - make

test_job:
  stage: test
  script:
    - make test
