stages:
  - build

before_script:

build-quartz:
  tags:
    - shell
    - quartz
  stage: build
  script:
    - mkdir build-libjustify && install-libjustify
    - cd build-libjustify
    - cmake -DCMAKE_INSTALL_PREFIX=../install-libjustify ../src/
    - make VERBOSE=1
    - make install
    - env CTEST_OUTPUT_ON_FAILURE=1 make test
