name: CMake Build and Test

on:
  push:
    branches:
      - cprintf_devel
  pull_request:
    branches:
      - cprintf_devel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        mkdir -p build
        cd build
        cmake ../src/
        
    - name: Build
      run: |
        cd build
        make

    - name: Test
      run: |
        cd build
        make test
